spring.application.name=consultancy-service

# Shared SMTP Settings
spring.mail.host=://gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Performance: Only load beans when needed (crucial for 0-replica wake-up)
spring.main.lazy-initialization=true
