# Local Test Credentials (using your dev app-password)
spring.mail.username=dev-testing@gmail.com
spring.mail.password=dev-app-password

# Disable Discovery locally since we are not using a Eureka container
eureka.client.enabled=false
spring.cloud.discovery.enabled=false