# Production Credentials from GitHub Secrets
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD_SECRET}

# Disable Discovery to save money and skip the "registry handshake" delay
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# If you have another service named 'madi-auth', call it via Azure Internal DNS
# services.auth-service.url=http://madi-auth-service
