spring.application.name=consultancy-service

# Profile-specific SMTP credentials
spring.mail.username=madi.java.consultancy@gmail.com
spring.mail.password=${MAIL_PASSWORD_SECRET}

#To initializze JVM without initially upload all beans in RAM, it will upload only when a request actually call them
spring.main.lazy-initialization=true
