spring.application.name=consultancy-service
eureka.client.service-url.defaultZone=https://azurewebsites.net
eureka.instance.hostname=${spring.application.name}.azurewebsites.net
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false

# Profile-specific SMTP credentials
spring.mail.username=madi.java.consultancy@gmail.com
spring.mail.password=${mail-password-secret}
