# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name maditech.online www.maditech.online;
    return 301 maditech.online$request_uri;
}

# Redirect HTTPS non-WWW to HTTPS WWW
server {
    listen 443 ssl;
    server_name maditech.online;
    
    ssl_certificate /etc/letsencrypt/live/maditech.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/maditech.online/privkey.pem;

    return 301 maditech.online$request_uri;
}

# Main Application Server Block
server {
    listen 443 ssl;
    server_name www.maditech.online;

    ssl_certificate /etc/letsencrypt/live/maditech.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/maditech.online/privkey.pem;

    root /usr/share/nginx/html;

    gzip on;
    gzip_http_version 1.1;
    gzip_disable "MSIE [1-6]\.";
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_comp_level 2;

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
