name: CI/CD - Build and deploy Spring Boot backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./microservices # <--- This forces all steps to look here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Angular
        working-directory: ./angular # Override just for this step
        run: |
          npm install
          npm run build -- --configuration=production --output-path=dist

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      
      - name: Build Java with Maven
        run: |
          # 1. Clean any old files to ensure a fresh start
          rm -rf src/main/resources/static/*
          mkdir -p src/main/resources/static
          
          # 2. Target the specific Angular 21 production output path
          # In Angular 21, it's usually dist/[project-name]/browser
          cp -r ../angular/dist/angular/browser/* src/main/resources/static/
          
          # 3. Build the JAR
          mvn package -DskipTests -Dskip.installnodenpm -Dskip.npm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/microservices/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Needed so the deploy action can see your Dockerfile

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/microservices/target

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MADICONSULTANCY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MADICONSULTANCY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MADICONSULTANCY_AZURE_SUBSCRIPTION_ID }}
          
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/microservices
          acrName: madi1registry
          acrUsername: ${{ secrets.MADICONSULTANCY_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          containerAppName: madi-consultancy
          resourceGroup: DefaultResourceGroup-CHN
          environmentVariables: >-
            SPRING_PROFILES_ACTIVE=prod
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://azurewebsites.net
            SPRING_MAIL_HOST=smtp.gmail.com
            SPRING_MAIL_PORT=587 
            SPRING_MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} 
            SPRING_MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
            SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
